BuildDebugSymbols: Convert arg (num cpus) to string for cros_build_lib.
BUG=chromium:1031380, b:187514311
TEST=./run_pytest service/artifacts_unittest.py

A 'bb' run to test this end-to-end uncovered this issue:

File "/b/s/w/ir/k/chromiumos_workspace/chromite/api/controller/artifacts.py", line 685, in BundleDebugSymbols
    result = artifacts.GenerateBreakpadSymbols(chroot,
  File "/b/s/w/ir/k/chromiumos_workspace/chromite/service/artifacts.py", line 848, in GenerateBreakpadSymbols
    result = cros_build_lib.run(
  File "/b/s/w/ir/k/chromiumos_workspace/chromite/lib/cros_build_lib.py", line 806, in run
    raise TypeError('All command elements must be bytes/strings: %r' % (cmd,))
TypeError: All command elements must be bytes/strings:
  ['cros_generate_breakpad_symbols', '--debug', '--board=atlas', '--jobs', 16, '--exclude-dir=firmware']

Change-Id: I71e5857c855c46ded5954079dc7c046cf15e4762
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/2806175
Tested-by: Michael Mortensen <mmortensen@google.com>
Commit-Queue: Michael Mortensen <mmortensen@google.com>
Reviewed-by: LaMont Jones <lamontjones@chromium.org>
Reviewed-by: Stephane Belmon <sbelmon@google.com>
(cherry picked from commit 9d12331d9c338df2aafc85d14960d9c86f600c96)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/2884918
Reviewed-by: Sergey Frolov <sfrolov@google.com>
Commit-Queue: Sergey Frolov <sfrolov@google.com>
Tested-by: Sergey Frolov <sfrolov@google.com>
Auto-Submit: Sergey Frolov <sfrolov@google.com>