service: sysroot: Fix arg for lookup service
We want to pass in the entire build_target object instead of individual
properties. This fixes the error:
Lookup service error: 'str' object has no attribute 'root'

BUG=b:316157442
TEST=CQ

Change-Id: I60501d6591c6e1f54679e29bb39d6c33afaec099
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/5166107
Reviewed-by: Nikhil Gumidelli <nikhilgm@google.com>
Auto-Submit: Cindy Lin <xcl@google.com>
Commit-Queue: Nikhil Gumidelli <nikhilgm@google.com>
Tested-by: Cindy Lin <xcl@google.com>