lib: osutils: Avoid copytree() for move(..., copy_function=)
shutil.copytree() is not a suitable copy_function for shutil.move().
While its signature matches, its behavior is not correct; specifically,
it doesn't handle copying a single file properly:

  $ touch foo
  $ python3 -c 'import shutil; shutil.copytree("foo", "bar")'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.10/shutil.py", line 557, in copytree
      with os.scandir(src) as itr:
  NotADirectoryError: [Errno 20] Not a directory: 'foo'

This naturally shows up much more subtly, because shutil.move() only
utilizes its copy_function when os.rename() doesn't work (e.g., moving
across bind mounts).

A manual test case that's more akin to the failures we actually see:

  mkdir -p a/foo c b
  touch a/foo/file
  sudo mount --bind c b
  python3 -c 'import shutil; shutil.move("a", "b", copy_function=shutil.copytree)'
  find a b
  sudo umount b
  rm -rf a b c

This produces errors like:

  Traceback (most recent call last):
    File "/usr/lib/python3.10/shutil.py", line 816, in move
      os.rename(src, real_dst)
  OSError: [Errno 18] Invalid cross-device link: 'a' -> 'b/a'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.10/shutil.py", line 832, in move
      copytree(src, real_dst, copy_function=copy_function,
    File "/usr/lib/python3.10/shutil.py", line 559, in copytree
      return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
    File "/usr/lib/python3.10/shutil.py", line 513, in _copytree
      raise Error(errors)
  shutil.Error: [('a/foo/file', 'b/a/foo/file', "[Errno 20] Not a directory: 'a/foo/file'")]
  a
  a/foo
  a/foo/file
  b
  b/a
  b/a/foo

I've faked something similar via mocks, by forcing os.rename() to fail.

BUG=b:281629868, b:265885353
TEST=manual
TEST=./run_tests

Change-Id: Idcefab877bd215d73877590be402ffc547ebe714
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4517559
Tested-by: Brian Norris <briannorris@chromium.org>
Commit-Queue: Brian Norris <briannorris@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>