DebugSymbols: materialize output of GatherSymbolFiles.
Ensure all symbol file processing is done, which will copy all
symbol files and return the full list.

Resolves error of calling 'len' on generator function.
For example, doing this (where real args are supplied
instead of ...):
  sym_file_list = artifacts.GatherSymbolFiles(...)
instead of this:
  sym_file_list = list(artifacts.GatherSymbolFiles(...))
results in:
   TypeError: object of type 'generator' has no len()

Found by using
  'bb -add' to turn on the DebugSymbols collection on staging builder.
but updates artifacts_unittest.py to verify and fix.

BUG=chromium:1031380, b:187514311
TEST=./run_pytest api/controller/artifacts_unittest.py

Change-Id: I0d2f84aef3231867415a720852fc1be872a6b0a2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/2818965
Tested-by: Michael Mortensen <mmortensen@google.com>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Michael Mortensen <mmortensen@google.com>
(cherry picked from commit 5044d27c529ec2ef674124b314e276cbd9afde1a)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/2888322
Reviewed-by: Sergey Frolov <sfrolov@google.com>
Commit-Queue: Sergey Frolov <sfrolov@google.com>
Tested-by: Sergey Frolov <sfrolov@google.com>