scripts: run_tests: update to python 3.11
We also need to update cros-query-types to import os directly.  This
logic isn't working with Python 3.11 for some reason.  The Python docs
say typing.TYPE_CHECKING should handle this, as should the annotations
import, but clearly that's not the case with 3.11, even though it is
working with 3.8.  Drop the minor optimization to workaround the issue
and unblock the upgrade.

$ ./scripts/generate_query_docs
generate_query_docs: Unhandled exception:
Traceback (most recent call last):
  File ".../scripts/generate_query_docs", line 51, in <module>
    main()
  File ".../scripts/generate_query_docs", line 47, in main
    wrapper3.DoMain()
  File ".../scripts/wrapper3.py", line 209, in DoMain
    commandline.ScriptWrapperMain(FindTarget)
  File ".../lib/commandline.py", line 1630, in ScriptWrapperMain
    _execute_target(target, argv, name)
  File ".../lib/commandline.py", line 1639, in _execute_target
    ret = target(argv[1:])
          ^^^^^^^^^^^^^^^^
  File ".../scripts/generate_query_docs.py", line 158, in main
    _gen_docs(buf)
  File ".../scripts/generate_query_docs.py", line 134, in _gen_docs
    hints = typing.get_type_hints(method)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/typing.py", line 2414, in get_type_hints
    hints[name] = _eval_type(value, globalns, localns)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/typing.py", line 395, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/typing.py", line 910, in _evaluate
    self.__forward_value__ = _eval_type(
                             ^^^^^^^^^^^
  File ".../lib/python3.11/typing.py", line 409, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/typing.py", line 409, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/typing.py", line 395, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/typing.py", line 905, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'os' is not defined

BUG=b:286270213
TEST=`./run_tests`

Change-Id: Ia068fd5c6f008bd6544225876845f0bde88a4945
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/6217920
Reviewed-by: Leandro Lovisolo <lovisolo@google.com>
Tested-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Leandro Lovisolo <lovisolo@google.com>
Auto-Submit: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>