lib: Allow non-pytest tests to mock things that are not cros_build_lib.run
Currently the unit tests in src/repohooks fail with
  KeyError: 'PYTEST_CURRENT_TEST'
when the checks for tests allowed to mock cros_build_lib.run
are performed.

Fix by falling back to a placeholder test descriptor.

minios_unittest.py is tweaked so that it doesn't conflict with the
fallback mechanism.

There are still tests in src/repohooks that _do_ want to mock run,
but they can be migrated to RunCommandMock() easily.

BUG=b:293038288
TEST=./pre-upload_unittests.py in src/repohooks

Change-Id: Ic7575895330b5557e2071537b6b46dca67f2b23d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4713933
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Tested-by: Trent Apted <tapted@chromium.org>
Commit-Queue: Trent Apted <tapted@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Auto-Submit: Trent Apted <tapted@chromium.org>